# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contacts_api import ContactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contacts_id_delete(self):
        """Test case for contacts_id_delete

        Contact delete  # noqa: E501
        """
        pass

    def test_contacts_id_get(self):
        """Test case for contacts_id_get

        Contact info  # noqa: E501
        """
        pass

    def test_contacts_id_head(self):
        """Test case for contacts_id_head

        Contact check  # noqa: E501
        """
        pass

    def test_contacts_id_patch(self):
        """Test case for contacts_id_patch

        Contact update  # noqa: E501
        """
        pass

    def test_contacts_id_transfers_latest_delete(self):
        """Test case for contacts_id_transfers_latest_delete

        Contact transfer cancel  # noqa: E501
        """
        pass

    def test_contacts_id_transfers_latest_get(self):
        """Test case for contacts_id_transfers_latest_get

        Contact transfer query  # noqa: E501
        """
        pass

    def test_contacts_id_transfers_latest_put(self):
        """Test case for contacts_id_transfers_latest_put

        Contact transfer approve  # noqa: E501
        """
        pass

    def test_contacts_id_transfers_post(self):
        """Test case for contacts_id_transfers_post

        Contact transfer request  # noqa: E501
        """
        pass

    def test_contacts_post(self):
        """Test case for contacts_post

        Contact create  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
