# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sec_dns_chg_type import SecDNSChgType  # noqa: E501
from swagger_client.rest import ApiException


class TestSecDNSChgType(unittest.TestCase):
    """SecDNSChgType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecDNSChgType(self):
        """Test SecDNSChgType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sec_dns_chg_type.SecDNSChgType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
