# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.domain_create_request_command import DomainCreateRequestCommand  # noqa: E501
from swagger_client.rest import ApiException


class TestDomainCreateRequestCommand(unittest.TestCase):
    """DomainCreateRequestCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainCreateRequestCommand(self):
        """Test DomainCreateRequestCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.domain_create_request_command.DomainCreateRequestCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
