# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.host_pa_name_type import HostPaNameType  # noqa: E501
from swagger_client.rest import ApiException


class TestHostPaNameType(unittest.TestCase):
    """HostPaNameType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostPaNameType(self):
        """Test HostPaNameType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.host_pa_name_type.HostPaNameType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
