# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.hosts_api import HostsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHostsApi(unittest.TestCase):
    """HostsApi unit test stubs"""

    def setUp(self):
        self.api = HostsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hosts_id_delete(self):
        """Test case for hosts_id_delete

        Host delete  # noqa: E501
        """
        pass

    def test_hosts_id_get(self):
        """Test case for hosts_id_get

        Host info  # noqa: E501
        """
        pass

    def test_hosts_id_head(self):
        """Test case for hosts_id_head

        Host check  # noqa: E501
        """
        pass

    def test_hosts_id_patch(self):
        """Test case for hosts_id_patch

        Host update  # noqa: E501
        """
        pass

    def test_hosts_post(self):
        """Test case for hosts_post

        Host create  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
