# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.domain_check_name_type import DomainCheckNameType  # noqa: E501
from swagger_client.rest import ApiException


class TestDomainCheckNameType(unittest.TestCase):
    """DomainCheckNameType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainCheckNameType(self):
        """Test DomainCheckNameType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.domain_check_name_type.DomainCheckNameType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
