# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.eppcom_label_type import EppcomLabelType  # noqa: E501
from swagger_client.rest import ApiException


class TestEppcomLabelType(unittest.TestCase):
    """EppcomLabelType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEppcomLabelType(self):
        """Test EppcomLabelType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.eppcom_label_type.EppcomLabelType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
