# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.epp_login_svc_type import EppLoginSvcType  # noqa: E501
from swagger_client.rest import ApiException


class TestEppLoginSvcType(unittest.TestCase):
    """EppLoginSvcType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEppLoginSvcType(self):
        """Test EppLoginSvcType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.epp_login_svc_type.EppLoginSvcType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
