# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.domains_api import DomainsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDomainsApi(unittest.TestCase):
    """DomainsApi unit test stubs"""

    def setUp(self):
        self.api = DomainsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_domains_id_delete(self):
        """Test case for domains_id_delete

        Domain delete  # noqa: E501
        """
        pass

    def test_domains_id_get(self):
        """Test case for domains_id_get

        Domain info  # noqa: E501
        """
        pass

    def test_domains_id_head(self):
        """Test case for domains_id_head

        Domain check  # noqa: E501
        """
        pass

    def test_domains_id_patch(self):
        """Test case for domains_id_patch

        Domain update  # noqa: E501
        """
        pass

    def test_domains_id_renewals_post(self):
        """Test case for domains_id_renewals_post

        Domain renew  # noqa: E501
        """
        pass

    def test_domains_id_transfers_latest_delete(self):
        """Test case for domains_id_transfers_latest_delete

        Domain transfer cancel  # noqa: E501
        """
        pass

    def test_domains_id_transfers_latest_get(self):
        """Test case for domains_id_transfers_latest_get

        Domain transfer query  # noqa: E501
        """
        pass

    def test_domains_id_transfers_latest_put(self):
        """Test case for domains_id_transfers_latest_put

        Domain transfer approve  # noqa: E501
        """
        pass

    def test_domains_id_transfers_post(self):
        """Test case for domains_id_transfers_post

        Domain transfer request  # noqa: E501
        """
        pass

    def test_domains_post(self):
        """Test case for domains_post

        Domain create  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
