# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainCreateType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_info': 'DomainAuthInfoType',
        'contact': 'list[DomainContactType]',
        'name': 'EppcomLabelType',
        'ns': 'DomainNsType',
        'period': 'DomainPeriodType',
        'registrant': 'EppcomClIDType'
    }

    attribute_map = {
        'auth_info': 'authInfo',
        'contact': 'contact',
        'name': 'name',
        'ns': 'ns',
        'period': 'period',
        'registrant': 'registrant'
    }

    def __init__(self, auth_info=None, contact=None, name=None, ns=None, period=None, registrant=None):  # noqa: E501
        """DomainCreateType - a model defined in Swagger"""  # noqa: E501
        self._auth_info = None
        self._contact = None
        self._name = None
        self._ns = None
        self._period = None
        self._registrant = None
        self.discriminator = None
        self.auth_info = auth_info
        if contact is not None:
            self.contact = contact
        self.name = name
        if ns is not None:
            self.ns = ns
        if period is not None:
            self.period = period
        if registrant is not None:
            self.registrant = registrant

    @property
    def auth_info(self):
        """Gets the auth_info of this DomainCreateType.  # noqa: E501


        :return: The auth_info of this DomainCreateType.  # noqa: E501
        :rtype: DomainAuthInfoType
        """
        return self._auth_info

    @auth_info.setter
    def auth_info(self, auth_info):
        """Sets the auth_info of this DomainCreateType.


        :param auth_info: The auth_info of this DomainCreateType.  # noqa: E501
        :type: DomainAuthInfoType
        """
        if auth_info is None:
            raise ValueError("Invalid value for `auth_info`, must not be `None`")  # noqa: E501

        self._auth_info = auth_info

    @property
    def contact(self):
        """Gets the contact of this DomainCreateType.  # noqa: E501


        :return: The contact of this DomainCreateType.  # noqa: E501
        :rtype: list[DomainContactType]
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this DomainCreateType.


        :param contact: The contact of this DomainCreateType.  # noqa: E501
        :type: list[DomainContactType]
        """

        self._contact = contact

    @property
    def name(self):
        """Gets the name of this DomainCreateType.  # noqa: E501


        :return: The name of this DomainCreateType.  # noqa: E501
        :rtype: EppcomLabelType
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DomainCreateType.


        :param name: The name of this DomainCreateType.  # noqa: E501
        :type: EppcomLabelType
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def ns(self):
        """Gets the ns of this DomainCreateType.  # noqa: E501


        :return: The ns of this DomainCreateType.  # noqa: E501
        :rtype: DomainNsType
        """
        return self._ns

    @ns.setter
    def ns(self, ns):
        """Sets the ns of this DomainCreateType.


        :param ns: The ns of this DomainCreateType.  # noqa: E501
        :type: DomainNsType
        """

        self._ns = ns

    @property
    def period(self):
        """Gets the period of this DomainCreateType.  # noqa: E501


        :return: The period of this DomainCreateType.  # noqa: E501
        :rtype: DomainPeriodType
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this DomainCreateType.


        :param period: The period of this DomainCreateType.  # noqa: E501
        :type: DomainPeriodType
        """

        self._period = period

    @property
    def registrant(self):
        """Gets the registrant of this DomainCreateType.  # noqa: E501


        :return: The registrant of this DomainCreateType.  # noqa: E501
        :rtype: EppcomClIDType
        """
        return self._registrant

    @registrant.setter
    def registrant(self, registrant):
        """Sets the registrant of this DomainCreateType.


        :param registrant: The registrant of this DomainCreateType.  # noqa: E501
        :type: EppcomClIDType
        """

        self._registrant = registrant

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainCreateType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainCreateType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
