# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainRenewType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cur_exp_date': 'date',
        'name': 'EppcomLabelType',
        'period': 'DomainPeriodType'
    }

    attribute_map = {
        'cur_exp_date': 'curExpDate',
        'name': 'name',
        'period': 'period'
    }

    def __init__(self, cur_exp_date=None, name=None, period=None):  # noqa: E501
        """DomainRenewType - a model defined in Swagger"""  # noqa: E501
        self._cur_exp_date = None
        self._name = None
        self._period = None
        self.discriminator = None
        self.cur_exp_date = cur_exp_date
        self.name = name
        if period is not None:
            self.period = period

    @property
    def cur_exp_date(self):
        """Gets the cur_exp_date of this DomainRenewType.  # noqa: E501


        :return: The cur_exp_date of this DomainRenewType.  # noqa: E501
        :rtype: date
        """
        return self._cur_exp_date

    @cur_exp_date.setter
    def cur_exp_date(self, cur_exp_date):
        """Sets the cur_exp_date of this DomainRenewType.


        :param cur_exp_date: The cur_exp_date of this DomainRenewType.  # noqa: E501
        :type: date
        """
        if cur_exp_date is None:
            raise ValueError("Invalid value for `cur_exp_date`, must not be `None`")  # noqa: E501

        self._cur_exp_date = cur_exp_date

    @property
    def name(self):
        """Gets the name of this DomainRenewType.  # noqa: E501


        :return: The name of this DomainRenewType.  # noqa: E501
        :rtype: EppcomLabelType
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DomainRenewType.


        :param name: The name of this DomainRenewType.  # noqa: E501
        :type: EppcomLabelType
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def period(self):
        """Gets the period of this DomainRenewType.  # noqa: E501


        :return: The period of this DomainRenewType.  # noqa: E501
        :rtype: DomainPeriodType
        """
        return self._period

    @period.setter
    def period(self, period):
        """Sets the period of this DomainRenewType.


        :param period: The period of this DomainRenewType.  # noqa: E501
        :type: DomainPeriodType
        """

        self._period = period

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainRenewType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainRenewType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
