# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainPaNameType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'value': 'str',
        'pa_result': 'bool'
    }

    attribute_map = {
        'value': '#value',
        'pa_result': '@paResult'
    }

    def __init__(self, value=None, pa_result=None):  # noqa: E501
        """DomainPaNameType - a model defined in Swagger"""  # noqa: E501
        self._value = None
        self._pa_result = None
        self.discriminator = None
        if value is not None:
            self.value = value
        if pa_result is not None:
            self.pa_result = pa_result

    @property
    def value(self):
        """Gets the value of this DomainPaNameType.  # noqa: E501


        :return: The value of this DomainPaNameType.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this DomainPaNameType.


        :param value: The value of this DomainPaNameType.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def pa_result(self):
        """Gets the pa_result of this DomainPaNameType.  # noqa: E501


        :return: The pa_result of this DomainPaNameType.  # noqa: E501
        :rtype: bool
        """
        return self._pa_result

    @pa_result.setter
    def pa_result(self, pa_result):
        """Sets the pa_result of this DomainPaNameType.


        :param pa_result: The pa_result of this DomainPaNameType.  # noqa: E501
        :type: bool
        """

        self._pa_result = pa_result

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainPaNameType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainPaNameType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
