# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainAddRemType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'contact': 'list[DomainContactType]',
        'ns': 'DomainNsType',
        'status': 'list[DomainStatusType]'
    }

    attribute_map = {
        'contact': 'contact',
        'ns': 'ns',
        'status': 'status'
    }

    def __init__(self, contact=None, ns=None, status=None):  # noqa: E501
        """DomainAddRemType - a model defined in Swagger"""  # noqa: E501
        self._contact = None
        self._ns = None
        self._status = None
        self.discriminator = None
        if contact is not None:
            self.contact = contact
        if ns is not None:
            self.ns = ns
        if status is not None:
            self.status = status

    @property
    def contact(self):
        """Gets the contact of this DomainAddRemType.  # noqa: E501


        :return: The contact of this DomainAddRemType.  # noqa: E501
        :rtype: list[DomainContactType]
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this DomainAddRemType.


        :param contact: The contact of this DomainAddRemType.  # noqa: E501
        :type: list[DomainContactType]
        """

        self._contact = contact

    @property
    def ns(self):
        """Gets the ns of this DomainAddRemType.  # noqa: E501


        :return: The ns of this DomainAddRemType.  # noqa: E501
        :rtype: DomainNsType
        """
        return self._ns

    @ns.setter
    def ns(self, ns):
        """Sets the ns of this DomainAddRemType.


        :param ns: The ns of this DomainAddRemType.  # noqa: E501
        :type: DomainNsType
        """

        self._ns = ns

    @property
    def status(self):
        """Gets the status of this DomainAddRemType.  # noqa: E501


        :return: The status of this DomainAddRemType.  # noqa: E501
        :rtype: list[DomainStatusType]
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DomainAddRemType.


        :param status: The status of this DomainAddRemType.  # noqa: E501
        :type: list[DomainStatusType]
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainAddRemType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainAddRemType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
