# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DomainInfoType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'auth_info': 'DomainAuthInfoType',
        'name': 'DomainInfoNameType'
    }

    attribute_map = {
        'auth_info': 'authInfo',
        'name': 'name'
    }

    def __init__(self, auth_info=None, name=None):  # noqa: E501
        """DomainInfoType - a model defined in Swagger"""  # noqa: E501
        self._auth_info = None
        self._name = None
        self.discriminator = None
        if auth_info is not None:
            self.auth_info = auth_info
        self.name = name

    @property
    def auth_info(self):
        """Gets the auth_info of this DomainInfoType.  # noqa: E501


        :return: The auth_info of this DomainInfoType.  # noqa: E501
        :rtype: DomainAuthInfoType
        """
        return self._auth_info

    @auth_info.setter
    def auth_info(self, auth_info):
        """Sets the auth_info of this DomainInfoType.


        :param auth_info: The auth_info of this DomainInfoType.  # noqa: E501
        :type: DomainAuthInfoType
        """

        self._auth_info = auth_info

    @property
    def name(self):
        """Gets the name of this DomainInfoType.  # noqa: E501


        :return: The name of this DomainInfoType.  # noqa: E501
        :rtype: DomainInfoNameType
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DomainInfoType.


        :param name: The name of this DomainInfoType.  # noqa: E501
        :type: DomainInfoNameType
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DomainInfoType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DomainInfoType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
