# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EppDcpPurposeType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'admin': 'bool',
        'contact': 'bool',
        'other': 'bool',
        'prov': 'bool'
    }

    attribute_map = {
        'admin': 'admin',
        'contact': 'contact',
        'other': 'other',
        'prov': 'prov'
    }

    def __init__(self, admin=False, contact=False, other=False, prov=False):  # noqa: E501
        """EppDcpPurposeType - a model defined in Swagger"""  # noqa: E501
        self._admin = None
        self._contact = None
        self._other = None
        self._prov = None
        self.discriminator = None
        if admin is not None:
            self.admin = admin
        if contact is not None:
            self.contact = contact
        if other is not None:
            self.other = other
        if prov is not None:
            self.prov = prov

    @property
    def admin(self):
        """Gets the admin of this EppDcpPurposeType.  # noqa: E501


        :return: The admin of this EppDcpPurposeType.  # noqa: E501
        :rtype: bool
        """
        return self._admin

    @admin.setter
    def admin(self, admin):
        """Sets the admin of this EppDcpPurposeType.


        :param admin: The admin of this EppDcpPurposeType.  # noqa: E501
        :type: bool
        """

        self._admin = admin

    @property
    def contact(self):
        """Gets the contact of this EppDcpPurposeType.  # noqa: E501


        :return: The contact of this EppDcpPurposeType.  # noqa: E501
        :rtype: bool
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """Sets the contact of this EppDcpPurposeType.


        :param contact: The contact of this EppDcpPurposeType.  # noqa: E501
        :type: bool
        """

        self._contact = contact

    @property
    def other(self):
        """Gets the other of this EppDcpPurposeType.  # noqa: E501


        :return: The other of this EppDcpPurposeType.  # noqa: E501
        :rtype: bool
        """
        return self._other

    @other.setter
    def other(self, other):
        """Sets the other of this EppDcpPurposeType.


        :param other: The other of this EppDcpPurposeType.  # noqa: E501
        :type: bool
        """

        self._other = other

    @property
    def prov(self):
        """Gets the prov of this EppDcpPurposeType.  # noqa: E501


        :return: The prov of this EppDcpPurposeType.  # noqa: E501
        :rtype: bool
        """
        return self._prov

    @prov.setter
    def prov(self, prov):
        """Sets the prov of this EppDcpPurposeType.


        :param prov: The prov of this EppDcpPurposeType.  # noqa: E501
        :type: bool
        """

        self._prov = prov

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EppDcpPurposeType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EppDcpPurposeType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
