# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EppTrIDType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'cl_trid': 'EppTrIDStringType',
        'sv_trid': 'EppTrIDStringType'
    }

    attribute_map = {
        'cl_trid': 'clTRID',
        'sv_trid': 'svTRID'
    }

    def __init__(self, cl_trid=None, sv_trid=None):  # noqa: E501
        """EppTrIDType - a model defined in Swagger"""  # noqa: E501
        self._cl_trid = None
        self._sv_trid = None
        self.discriminator = None
        if cl_trid is not None:
            self.cl_trid = cl_trid
        self.sv_trid = sv_trid

    @property
    def cl_trid(self):
        """Gets the cl_trid of this EppTrIDType.  # noqa: E501


        :return: The cl_trid of this EppTrIDType.  # noqa: E501
        :rtype: EppTrIDStringType
        """
        return self._cl_trid

    @cl_trid.setter
    def cl_trid(self, cl_trid):
        """Sets the cl_trid of this EppTrIDType.


        :param cl_trid: The cl_trid of this EppTrIDType.  # noqa: E501
        :type: EppTrIDStringType
        """

        self._cl_trid = cl_trid

    @property
    def sv_trid(self):
        """Gets the sv_trid of this EppTrIDType.  # noqa: E501


        :return: The sv_trid of this EppTrIDType.  # noqa: E501
        :rtype: EppTrIDStringType
        """
        return self._sv_trid

    @sv_trid.setter
    def sv_trid(self, sv_trid):
        """Sets the sv_trid of this EppTrIDType.


        :param sv_trid: The sv_trid of this EppTrIDType.  # noqa: E501
        :type: EppTrIDStringType
        """
        if sv_trid is None:
            raise ValueError("Invalid value for `sv_trid`, must not be `None`")  # noqa: E501

        self._sv_trid = sv_trid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EppTrIDType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EppTrIDType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
