# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EppDcpStatementType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'purpose': 'EppDcpPurposeType',
        'recipient': 'EppDcpRecipientType',
        'retention': 'EppDcpRetentionType'
    }

    attribute_map = {
        'purpose': 'purpose',
        'recipient': 'recipient',
        'retention': 'retention'
    }

    def __init__(self, purpose=None, recipient=None, retention=None):  # noqa: E501
        """EppDcpStatementType - a model defined in Swagger"""  # noqa: E501
        self._purpose = None
        self._recipient = None
        self._retention = None
        self.discriminator = None
        self.purpose = purpose
        self.recipient = recipient
        self.retention = retention

    @property
    def purpose(self):
        """Gets the purpose of this EppDcpStatementType.  # noqa: E501


        :return: The purpose of this EppDcpStatementType.  # noqa: E501
        :rtype: EppDcpPurposeType
        """
        return self._purpose

    @purpose.setter
    def purpose(self, purpose):
        """Sets the purpose of this EppDcpStatementType.


        :param purpose: The purpose of this EppDcpStatementType.  # noqa: E501
        :type: EppDcpPurposeType
        """
        if purpose is None:
            raise ValueError("Invalid value for `purpose`, must not be `None`")  # noqa: E501

        self._purpose = purpose

    @property
    def recipient(self):
        """Gets the recipient of this EppDcpStatementType.  # noqa: E501


        :return: The recipient of this EppDcpStatementType.  # noqa: E501
        :rtype: EppDcpRecipientType
        """
        return self._recipient

    @recipient.setter
    def recipient(self, recipient):
        """Sets the recipient of this EppDcpStatementType.


        :param recipient: The recipient of this EppDcpStatementType.  # noqa: E501
        :type: EppDcpRecipientType
        """
        if recipient is None:
            raise ValueError("Invalid value for `recipient`, must not be `None`")  # noqa: E501

        self._recipient = recipient

    @property
    def retention(self):
        """Gets the retention of this EppDcpStatementType.  # noqa: E501


        :return: The retention of this EppDcpStatementType.  # noqa: E501
        :rtype: EppDcpRetentionType
        """
        return self._retention

    @retention.setter
    def retention(self, retention):
        """Sets the retention of this EppDcpStatementType.


        :param retention: The retention of this EppDcpStatementType.  # noqa: E501
        :type: EppDcpRetentionType
        """
        if retention is None:
            raise ValueError("Invalid value for `retention`, must not be `None`")  # noqa: E501

        self._retention = retention

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EppDcpStatementType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EppDcpStatementType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
