# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EppSvcMenuType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'lang': 'list[str]',
        'obj_uri': 'list[str]',
        'svc_extension': 'EppExtURIType',
        'version': 'list[EppVersionType]'
    }

    attribute_map = {
        'lang': 'lang',
        'obj_uri': 'objURI',
        'svc_extension': 'svcExtension',
        'version': 'version'
    }

    def __init__(self, lang=None, obj_uri=None, svc_extension=None, version=None):  # noqa: E501
        """EppSvcMenuType - a model defined in Swagger"""  # noqa: E501
        self._lang = None
        self._obj_uri = None
        self._svc_extension = None
        self._version = None
        self.discriminator = None
        if lang is not None:
            self.lang = lang
        if obj_uri is not None:
            self.obj_uri = obj_uri
        if svc_extension is not None:
            self.svc_extension = svc_extension
        if version is not None:
            self.version = version

    @property
    def lang(self):
        """Gets the lang of this EppSvcMenuType.  # noqa: E501


        :return: The lang of this EppSvcMenuType.  # noqa: E501
        :rtype: list[str]
        """
        return self._lang

    @lang.setter
    def lang(self, lang):
        """Sets the lang of this EppSvcMenuType.


        :param lang: The lang of this EppSvcMenuType.  # noqa: E501
        :type: list[str]
        """

        self._lang = lang

    @property
    def obj_uri(self):
        """Gets the obj_uri of this EppSvcMenuType.  # noqa: E501


        :return: The obj_uri of this EppSvcMenuType.  # noqa: E501
        :rtype: list[str]
        """
        return self._obj_uri

    @obj_uri.setter
    def obj_uri(self, obj_uri):
        """Sets the obj_uri of this EppSvcMenuType.


        :param obj_uri: The obj_uri of this EppSvcMenuType.  # noqa: E501
        :type: list[str]
        """

        self._obj_uri = obj_uri

    @property
    def svc_extension(self):
        """Gets the svc_extension of this EppSvcMenuType.  # noqa: E501


        :return: The svc_extension of this EppSvcMenuType.  # noqa: E501
        :rtype: EppExtURIType
        """
        return self._svc_extension

    @svc_extension.setter
    def svc_extension(self, svc_extension):
        """Sets the svc_extension of this EppSvcMenuType.


        :param svc_extension: The svc_extension of this EppSvcMenuType.  # noqa: E501
        :type: EppExtURIType
        """

        self._svc_extension = svc_extension

    @property
    def version(self):
        """Gets the version of this EppSvcMenuType.  # noqa: E501


        :return: The version of this EppSvcMenuType.  # noqa: E501
        :rtype: list[EppVersionType]
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this EppSvcMenuType.


        :param version: The version of this EppSvcMenuType.  # noqa: E501
        :type: list[EppVersionType]
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EppSvcMenuType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EppSvcMenuType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
