# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SecDNSUpdateType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'urgent': 'bool',
        'add': 'SecDNSDsOrKeyType',
        'chg': 'SecDNSChgType',
        'rem': 'SecDNSRemType'
    }

    attribute_map = {
        'urgent': '@urgent',
        'add': 'add',
        'chg': 'chg',
        'rem': 'rem'
    }

    def __init__(self, urgent=None, add=None, chg=None, rem=None):  # noqa: E501
        """SecDNSUpdateType - a model defined in Swagger"""  # noqa: E501
        self._urgent = None
        self._add = None
        self._chg = None
        self._rem = None
        self.discriminator = None
        if urgent is not None:
            self.urgent = urgent
        if add is not None:
            self.add = add
        if chg is not None:
            self.chg = chg
        if rem is not None:
            self.rem = rem

    @property
    def urgent(self):
        """Gets the urgent of this SecDNSUpdateType.  # noqa: E501


        :return: The urgent of this SecDNSUpdateType.  # noqa: E501
        :rtype: bool
        """
        return self._urgent

    @urgent.setter
    def urgent(self, urgent):
        """Sets the urgent of this SecDNSUpdateType.


        :param urgent: The urgent of this SecDNSUpdateType.  # noqa: E501
        :type: bool
        """

        self._urgent = urgent

    @property
    def add(self):
        """Gets the add of this SecDNSUpdateType.  # noqa: E501


        :return: The add of this SecDNSUpdateType.  # noqa: E501
        :rtype: SecDNSDsOrKeyType
        """
        return self._add

    @add.setter
    def add(self, add):
        """Sets the add of this SecDNSUpdateType.


        :param add: The add of this SecDNSUpdateType.  # noqa: E501
        :type: SecDNSDsOrKeyType
        """

        self._add = add

    @property
    def chg(self):
        """Gets the chg of this SecDNSUpdateType.  # noqa: E501


        :return: The chg of this SecDNSUpdateType.  # noqa: E501
        :rtype: SecDNSChgType
        """
        return self._chg

    @chg.setter
    def chg(self, chg):
        """Sets the chg of this SecDNSUpdateType.


        :param chg: The chg of this SecDNSUpdateType.  # noqa: E501
        :type: SecDNSChgType
        """

        self._chg = chg

    @property
    def rem(self):
        """Gets the rem of this SecDNSUpdateType.  # noqa: E501


        :return: The rem of this SecDNSUpdateType.  # noqa: E501
        :rtype: SecDNSRemType
        """
        return self._rem

    @rem.setter
    def rem(self, rem):
        """Sets the rem of this SecDNSUpdateType.


        :param rem: The rem of this SecDNSUpdateType.  # noqa: E501
        :type: SecDNSRemType
        """

        self._rem = rem

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecDNSUpdateType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecDNSUpdateType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
