# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SecDNSChgType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'max_sig_life': 'SecDNSMaxSigLifeType'
    }

    attribute_map = {
        'max_sig_life': 'maxSigLife'
    }

    def __init__(self, max_sig_life=None):  # noqa: E501
        """SecDNSChgType - a model defined in Swagger"""  # noqa: E501
        self._max_sig_life = None
        self.discriminator = None
        if max_sig_life is not None:
            self.max_sig_life = max_sig_life

    @property
    def max_sig_life(self):
        """Gets the max_sig_life of this SecDNSChgType.  # noqa: E501


        :return: The max_sig_life of this SecDNSChgType.  # noqa: E501
        :rtype: SecDNSMaxSigLifeType
        """
        return self._max_sig_life

    @max_sig_life.setter
    def max_sig_life(self, max_sig_life):
        """Sets the max_sig_life of this SecDNSChgType.


        :param max_sig_life: The max_sig_life of this SecDNSChgType.  # noqa: E501
        :type: SecDNSMaxSigLifeType
        """

        self._max_sig_life = max_sig_life

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecDNSChgType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecDNSChgType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
