# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SecDNSKeyDataType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alg': 'int',
        'flags': 'int',
        'protocol': 'int',
        'pub_key': 'SecDNSKeyType'
    }

    attribute_map = {
        'alg': 'alg',
        'flags': 'flags',
        'protocol': 'protocol',
        'pub_key': 'pubKey'
    }

    def __init__(self, alg=None, flags=None, protocol=None, pub_key=None):  # noqa: E501
        """SecDNSKeyDataType - a model defined in Swagger"""  # noqa: E501
        self._alg = None
        self._flags = None
        self._protocol = None
        self._pub_key = None
        self.discriminator = None
        self.alg = alg
        self.flags = flags
        self.protocol = protocol
        self.pub_key = pub_key

    @property
    def alg(self):
        """Gets the alg of this SecDNSKeyDataType.  # noqa: E501


        :return: The alg of this SecDNSKeyDataType.  # noqa: E501
        :rtype: int
        """
        return self._alg

    @alg.setter
    def alg(self, alg):
        """Sets the alg of this SecDNSKeyDataType.


        :param alg: The alg of this SecDNSKeyDataType.  # noqa: E501
        :type: int
        """
        if alg is None:
            raise ValueError("Invalid value for `alg`, must not be `None`")  # noqa: E501

        self._alg = alg

    @property
    def flags(self):
        """Gets the flags of this SecDNSKeyDataType.  # noqa: E501


        :return: The flags of this SecDNSKeyDataType.  # noqa: E501
        :rtype: int
        """
        return self._flags

    @flags.setter
    def flags(self, flags):
        """Sets the flags of this SecDNSKeyDataType.


        :param flags: The flags of this SecDNSKeyDataType.  # noqa: E501
        :type: int
        """
        if flags is None:
            raise ValueError("Invalid value for `flags`, must not be `None`")  # noqa: E501

        self._flags = flags

    @property
    def protocol(self):
        """Gets the protocol of this SecDNSKeyDataType.  # noqa: E501


        :return: The protocol of this SecDNSKeyDataType.  # noqa: E501
        :rtype: int
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol):
        """Sets the protocol of this SecDNSKeyDataType.


        :param protocol: The protocol of this SecDNSKeyDataType.  # noqa: E501
        :type: int
        """
        if protocol is None:
            raise ValueError("Invalid value for `protocol`, must not be `None`")  # noqa: E501

        self._protocol = protocol

    @property
    def pub_key(self):
        """Gets the pub_key of this SecDNSKeyDataType.  # noqa: E501


        :return: The pub_key of this SecDNSKeyDataType.  # noqa: E501
        :rtype: SecDNSKeyType
        """
        return self._pub_key

    @pub_key.setter
    def pub_key(self, pub_key):
        """Sets the pub_key of this SecDNSKeyDataType.


        :param pub_key: The pub_key of this SecDNSKeyDataType.  # noqa: E501
        :type: SecDNSKeyType
        """
        if pub_key is None:
            raise ValueError("Invalid value for `pub_key`, must not be `None`")  # noqa: E501

        self._pub_key = pub_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SecDNSKeyDataType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SecDNSKeyDataType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
