# coding: utf-8

"""
    RESTful EPP

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class CommonApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def messages_get(self, repp_cltrid, repp_svcs, accept_language, **kwargs):  # noqa: E501
        """Poll request  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.messages_get(repp_cltrid, repp_svcs, accept_language, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repp_cltrid: Client transaction identifier (required)
        :param str repp_svcs: Namespace used (required)
        :param str accept_language: Language used for response (required)
        :param str body: Default request body for XML of JSON message
        :param str repp_svcs_ext: Extension namespace used
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.messages_get_with_http_info(repp_cltrid, repp_svcs, accept_language, **kwargs)  # noqa: E501
        else:
            (data) = self.messages_get_with_http_info(repp_cltrid, repp_svcs, accept_language, **kwargs)  # noqa: E501
            return data

    def messages_get_with_http_info(self, repp_cltrid, repp_svcs, accept_language, **kwargs):  # noqa: E501
        """Poll request  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.messages_get_with_http_info(repp_cltrid, repp_svcs, accept_language, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repp_cltrid: Client transaction identifier (required)
        :param str repp_svcs: Namespace used (required)
        :param str accept_language: Language used for response (required)
        :param str body: Default request body for XML of JSON message
        :param str repp_svcs_ext: Extension namespace used
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repp_cltrid', 'repp_svcs', 'accept_language', 'body', 'repp_svcs_ext']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method messages_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repp_cltrid' is set
        if ('repp_cltrid' not in params or
                params['repp_cltrid'] is None):
            raise ValueError("Missing the required parameter `repp_cltrid` when calling `messages_get`")  # noqa: E501
        # verify the required parameter 'repp_svcs' is set
        if ('repp_svcs' not in params or
                params['repp_svcs'] is None):
            raise ValueError("Missing the required parameter `repp_svcs` when calling `messages_get`")  # noqa: E501
        # verify the required parameter 'accept_language' is set
        if ('accept_language' not in params or
                params['accept_language'] is None):
            raise ValueError("Missing the required parameter `accept_language` when calling `messages_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'repp_cltrid' in params:
            header_params['REPP-cltrid'] = params['repp_cltrid']  # noqa: E501
        if 'repp_svcs' in params:
            header_params['REPP-svcs'] = params['repp_svcs']  # noqa: E501
        if 'repp_svcs_ext' in params:
            header_params['REPP-svcs-ext'] = params['repp_svcs_ext']  # noqa: E501
        if 'accept_language' in params:
            header_params['Accept-Language'] = params['accept_language']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/epp+json', 'application/epp+xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/epp+json', 'application/epp+xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/messages', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def messages_id_head(self, repp_cltrid, repp_svcs, accept_language, id, **kwargs):  # noqa: E501
        """Poll ack  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.messages_id_head(repp_cltrid, repp_svcs, accept_language, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repp_cltrid: Client transaction identifier (required)
        :param str repp_svcs: Namespace used (required)
        :param str accept_language: Language used for response (required)
        :param str id: Object identifier (required)
        :param str body: Default request body for XML of JSON message
        :param str repp_svcs_ext: Extension namespace used
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.messages_id_head_with_http_info(repp_cltrid, repp_svcs, accept_language, id, **kwargs)  # noqa: E501
        else:
            (data) = self.messages_id_head_with_http_info(repp_cltrid, repp_svcs, accept_language, id, **kwargs)  # noqa: E501
            return data

    def messages_id_head_with_http_info(self, repp_cltrid, repp_svcs, accept_language, id, **kwargs):  # noqa: E501
        """Poll ack  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.messages_id_head_with_http_info(repp_cltrid, repp_svcs, accept_language, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str repp_cltrid: Client transaction identifier (required)
        :param str repp_svcs: Namespace used (required)
        :param str accept_language: Language used for response (required)
        :param str id: Object identifier (required)
        :param str body: Default request body for XML of JSON message
        :param str repp_svcs_ext: Extension namespace used
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['repp_cltrid', 'repp_svcs', 'accept_language', 'id', 'body', 'repp_svcs_ext']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method messages_id_head" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'repp_cltrid' is set
        if ('repp_cltrid' not in params or
                params['repp_cltrid'] is None):
            raise ValueError("Missing the required parameter `repp_cltrid` when calling `messages_id_head`")  # noqa: E501
        # verify the required parameter 'repp_svcs' is set
        if ('repp_svcs' not in params or
                params['repp_svcs'] is None):
            raise ValueError("Missing the required parameter `repp_svcs` when calling `messages_id_head`")  # noqa: E501
        # verify the required parameter 'accept_language' is set
        if ('accept_language' not in params or
                params['accept_language'] is None):
            raise ValueError("Missing the required parameter `accept_language` when calling `messages_id_head`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `messages_id_head`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'repp_cltrid' in params:
            header_params['REPP-cltrid'] = params['repp_cltrid']  # noqa: E501
        if 'repp_svcs' in params:
            header_params['REPP-svcs'] = params['repp_svcs']  # noqa: E501
        if 'repp_svcs_ext' in params:
            header_params['REPP-svcs-ext'] = params['repp_svcs_ext']  # noqa: E501
        if 'accept_language' in params:
            header_params['Accept-Language'] = params['accept_language']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/epp+json', 'application/epp+xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/messages/{id}', 'HEAD',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def root_get(self, accept_language, **kwargs):  # noqa: E501
        """Hello  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_get(accept_language, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str accept_language: Language used for response (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.root_get_with_http_info(accept_language, **kwargs)  # noqa: E501
        else:
            (data) = self.root_get_with_http_info(accept_language, **kwargs)  # noqa: E501
            return data

    def root_get_with_http_info(self, accept_language, **kwargs):  # noqa: E501
        """Hello  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_get_with_http_info(accept_language, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str accept_language: Language used for response (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['accept_language']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method root_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'accept_language' is set
        if ('accept_language' not in params or
                params['accept_language'] is None):
            raise ValueError("Missing the required parameter `accept_language` when calling `root_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}
        if 'accept_language' in params:
            header_params['Accept-Language'] = params['accept_language']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/epp+json', 'application/epp+xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
